apiVersion: apps/v1
kind: Deployment
metadata:
  name: groupfactory
  namespace: groupfactory
  labels:
    app: groupfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groupfactory
  template:
    metadata:
      labels:
        app: groupfactory 
    spec:
      containers:
      - name: groupfactory
        image: <registry-url>/groupfactory:latest
        envFrom:
          - configMapRef:
              name: telegram-config
          - secretRef:
              name: groupfactory-tg-auth
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: groupfactory-tg-auth
              key: MONGODB_URI
        - name: MONGODB_DATABASE
          value: "imsuserbot"
        - name: MONGODB_COLLECTION
          value: "ghconfig"